?cxx/ClassSys.*xx `%s/vector<const /vector</`
  ?cxx/ClassCns.hxx `%s/vector<const /vector</`
  ?cxx/VirusAnalysis.cxx ?cxx/AssistantCns.cxx `%s/<const /</`
  From https://github.com/SwuduSusuwu/SubStack/actions/runs/11118888813/job/30893206184 :
  ```
  [2024-10-01 04:56:40] [build-stdout] In file included from ./cxx/ClassSys.hxx:14:
  [2024-10-01 04:56:40] [build-stdout] In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/vector:64:
  [2024-10-01 04:56:40] [build-stdout] /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:435:7: error: static_assert failed due to requirement 'is_same<std::basic_string<char, std::char_traits<char>, std::allocator<char>>, const std::basic_string<char, std::char_traits<char>, std::allocator<char>>>::value' "std::vector must have a non-const, non-volatile value_type"
  [2024-10-01 04:56:40] [build-stdout]       static_assert(is_same<typename remove_cv<_Tp>::type, _Tp>::value,
  [2024-10-01 04:56:40] [build-stdout]       ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  [2024-10-01 04:56:40] [build-stdout] ./cxx/ClassSys.hxx:27:151: note: in instantiation of template class 'std::vector<const std::basic_string<char>>' requested here
  [2024-10-01 04:56:40] [build-stdout] const pid_t execvesFork(/* const
  std::string &pathname, -- `execve` requires `&pathname == &argv[0]` */
  const std::vector<const std::string> &argvS = {}, const
  std::vector<const std::string> &envpS = {});
  ```
  Fix this. Am unsure what causes GitHub's compiler to fail on `const std::vectors<const std::string>`, but it does, thus this commit replaces `vector<const` with `vector<`.
    Now, not just `./build --debug && ./a.out` has all tests pass;
    `./build --release && ./a.out` has all tests pass too.
    On _Android_ (*aarch64*), the `--debug` build is ~2.9mb, whereas the `--release` build is
    ~256kb.

?posts/VirusAnalysis.md /* Include this */
  Plus
  ```
  %s/^less /`less` /
  ```
  /* typo fix */